export enum TypeAction {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    REQUEST_FAILURE = 'REQUEST_FAILURE',
    REQUEST_SUCCESS = 'REQUEST_SUCCESS',
    CLIENT_CREDENTIALS = 'CLIENT_CREDENTIALS',
    CLIENT_CREDENTIALS_SUCCESS = 'CLIENT_CREDENTIALS_SUCCESS',
};