export enum AddressActionState {
    GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST',
    SET_ADDRESS_REQUEST = 'SET_ADDRESS_REQUEST',
    CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST',
    UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST',
    DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST',
};