export enum ChargeActionState {
    GET_CHARGES_REQUEST = 'GET_CHARGES_REQUEST',
    SET_CHARGES_REQUEST = 'SET_CHARGES_REQUEST',
    CREATE_CHARGES_REQUEST = 'CREATE_CHARGES_REQUEST',
    UPDATE_CHARGES_REQUEST = 'UPDATE_CHARGES_REQUEST',
    DELETE_CHARGES_REQUEST = 'DELETE_CHARGES_REQUEST',
};
