export enum ColabActionState {
    GET_COLABS_REQUEST = 'GET_COLABS_REQUEST',
    SET_COLABS_REQUEST = 'SET_COLABS_REQUEST',
    CREATE_COLABS_REQUEST = 'CREATE_COLABS_REQUEST',
    UPDATE_COLABS_REQUEST = 'UPDATE_COLABS_REQUEST',
    DELETE_COLABS_REQUEST = 'DELETE_COLABS_REQUEST',
};