export enum RouteActionState {
    GET_ROUTES_REQUEST = 'GET_ROUTES_REQUEST',
    SET_ROUTES_REQUEST = 'SET_ROUTES_REQUEST',
    CREATE_ROUTES_REQUEST = 'CREATE_ROUTES_REQUEST',
    UPDATE_ROUTES_REQUEST = 'UPDATE_ROUTES_REQUEST',
    DELETE_ROUTES_REQUEST = 'DELETE_ROUTES_REQUEST',
};