export enum VehicleActionState {
    GET_VEHICLES_REQUEST = 'GET_VEHICLES_REQUEST',
    SET_VEHICLES_REQUEST = 'SET_VEHICLES_REQUEST',
    CREATE_VEHICLES_REQUEST = 'CREATE_VEHICLES_REQUEST',
    UPDATE_VEHICLES_REQUEST = 'UPDATE_VEHICLES_REQUEST',
    DELETE_VEHICLES_REQUEST = 'DELETE_VEHICLES_REQUEST',
};