export enum DeliveryActionState {
    GET_DELIVERIES_REQUEST = 'GET_DELIVERIES_REQUEST',
    SET_DELIVERIES_REQUEST = 'SET_DELIVERIES_REQUEST',
    CREATE_DELIVERIES_REQUEST = 'CREATE_DELIVERIES_REQUEST',
    UPDATE_DELIVERIES_REQUEST = 'UPDATE_DELIVERIES_REQUEST',
    DELETE_DELIVERIES_REQUEST = 'DELETE_DELIVERIES_REQUEST',
};